# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Validation Service Unittests via pytest

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ dev/dc, dev/dr , hot/dr, hot/dc]

jobs:
  build:
    name:  Validation Service unittests (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      matrix:
        os: [ macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup testing environment
        run: >
          pip install -r test_requirements.txt

      - name: Test with unittest
        run: |
          pytest tests.py


